### ISSUE TITLE
Format document not running prettier?

### ISSUE THREAD

**Issue by lorensr** [prettier/prettier-vscode#388]
What's the best way to diagnose this issue? I have prettier installed and enabled. It used to work fine. I don't know when exactly it stopped working. When I have for instance this:

```jsx
  <p>test</p>
<Modal     open={this.state.addingReview}        ></Modal>
```

And run `Format Document`, it results in this:

```jsx
<p>test</p>
<Modal open={this.state.addingReview}      ></Modal>
```

Whereas running prettier from the command line results in:

```jsx
<p>test</p>
<Modal open={this.state.addingReview} />
```

**Comment by ajhyndman** [comment]
Seems to me like the most recent version of VS Code has lost compatibility with this extension.

**Comment by RobinMalfait** [comment]
@ajhyndman I'm on the latest vscode version and the extensions still works for me.

@lorensr Do you see any errors in the prettier output window? (press the right bottom `prettier` item)

**Comment by CiGit** [comment]
Do you have multiple formatter installed?
eslintIntegration?

**Comment by ajhyndman** [comment]
Whoah, that's weird... Thanks for the suggestion, @CiGit .  I disabled the ESLint extension, and re-enabled it.  Now prettier seems to be running again?

It's possible I changed something else without realizing, as well.  I'll report back if any issues resurface.

**Comment by lorensr** [comment]
Disabling eslint has no effect. @RobinMalfait do you mean this output tab? It's not an option.

![image](https://user-images.githubusercontent.com/251288/37174834-bc0efc28-22e5-11e8-9c89-97b1beadf020.png)

Prettier is def enabled:

![image](https://user-images.githubusercontent.com/251288/37174915-eb806762-22e5-11e8-9b29-c16beca41e37.png)

Here are other extensions:

![image](https://user-images.githubusercontent.com/251288/37174953-09745fee-22e6-11e8-90b3-e1293a34fb8f.png)

**Comment by Bassetts** [comment]
Prettier appears to have stopped working for me on version 1.22.0-insider. I don't have ESLint installed so this is definitely not causing the issue.

**Comment by CiGit** [comment]
@lorensr Seems the extension did not start. Can you take a look at dev console?
Help -> toggle developer tools -> console

Try reinstalling:
- Uninstall extension
- Close VSCode
- Be sure `$HOME/.vscode{,-insider}/extensions/esbenp.prettier-vscode-1.2.2` doesn't exist
- Install extension

**Comment by sstimac** [comment]
What happened in my case, is VSC update deleted some of my user settings, one of which was the `formatOnSave`
, which is why the extension seemed broken ( as i'm used to format on save ).

Setting the property back was easy enough. If that's the case, check if you have 
`"editor.formatOnSave": true` set within the settings.

**Comment by lorensr** [comment]
My settings were intact. Here was the error:

![image](https://user-images.githubusercontent.com/251288/37224162-a6104466-23a0-11e8-82e9-0d727e0e7791.png)

`Activating extension `esbenp.prettier-vscode` failed: Cannot find module 'resolve'.`

Fixed by reinstalling. Did have to manually delete the folder. Thank you CiGit!

**Comment by umlx5h** [comment]
I have a same problem. It used to work.
I tried to solve problem by @CiGit and @sstimac workaround. But It couldn't be solved.
This problem was already solved?
I use a latest version vscode(1.21.1) and this extension(1.2.2).

**Comment by CiGit** [comment]
If you have a missing dependency, reinstalling is the only thing I see.

**Comment by danawoodman** [comment]
For future idiots like me, make sure the file you're saving isn't in your `.prettierignore` file! 🤦‍♂️

**Comment by ag-kylemh** [comment]
I had this problem as well. It seemed as though disabling and re-enabling the eslint-integration rule resolved the issue for me. I did also take re-installation steps described above to the letter, but it didn't resolve my issue. Format on save and format document didn't work, but format selection did.

**Comment by amypellegrini** [comment]
I run into this problem and in my particular case the "solution" required to address flow errors first, as prettier won't run if there are flow errors.

**Comment by guiccbr** [comment]
I had an error on my code that was preventing prettier to run. Was able to see the error through the output panel and selecting `prettier` on the dropdown on the right, as suggested by @RobinMalfait.

**Comment by skube** [comment]
For me, I'm noticing if I remove the `plugin:prettier/recommended` from `.eslintrc`:
```
"extends": ["airbnb","plugin:prettier/recommended"]
```
It works again (but obviously under different rules) so I dunno

**Comment by peterbe** [comment]
My problem was that I had `prettier` in my `frontend/package.json` but nothing in `frontend/node_modules`. The reason it's like that is because `node_modules` is installed inside a docker container. 

My executable `prettier` is `/Users/peterbe/.config/yarn/global/node_modules/.bin/prettier` but for some reason, in this project, it couldn't use that.

**Comment by karlhorky** [comment]
For me the problem was caused by a large document that was taking a few seconds to format.

Increasing `"editor.formatOnSaveTimeout"` fixed the problem: https://code.visualstudio.com/updates/v1_22#_configurable-format-on-save-timeout

**Comment by xerosanyam** [comment]
I had a keyword delete, because of which prettier was showing output but not formatting the code

**Comment by Norfeldt** [comment]
> My problem was that I had `prettier` in my `frontend/package.json` but nothing in `frontend/node_modules`. The reason it's like that is because `node_modules` is installed inside a docker container.
> 
> My executable `prettier` is `/Users/peterbe/.config/yarn/global/node_modules/.bin/prettier` but for some reason, in this project, it couldn't use that.

Thank you! You pointed me to look into the `package.json` to find some prettier stuff that needed to be removed.

**Comment by simonhaenisch** [comment]
Just updated to 1.33.0 and suddenly had the same problem of it not working on save... the way I got it fixed was that I ran "Format Document" through the command palette. Then VS Code showed an extension that there are multiple formatters for .ts files installed and asked me to set a default, which added

```json
"[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
}
```

to my settings. Maybe that's a feature of the new version but sadly it doesn't show the modal when trying to run the formatter by saving the file, but the default formatter thing seems to be a nice feature.

**Comment by evertonbuild** [comment]
thanks @simonhaenisch 

I did not know how to change this file, so I am sharing this link that can be useful for anyone who has the same problem.

https://code.visualstudio.com/docs/getstarted/settings#_language-specific-editor-settings

**Comment by verlok** [comment]
I was getting the error "Prettier cannot format code".
Uninstalling and reinstalling Prettier worked for me too.

**Comment by jessepinho** [comment]
For those of you using TypeScript, perhaps this is your issue: I noticed this in my VSCode `settings.json`:

```JSON
  "[typescript]": {
    "editor.defaultFormatter": "vscode.typescript-language-features"
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "vscode.typescript-language-features"
  },
```

This was blocking Prettier from running on my `.ts` and `.tsx` files. Removing these fixed the issue for me.

**Comment by klippx** [comment]
For me this was broken in `1.34.0` and I tracked it down to config.json:

```
"prettier.eslintIntegration": true,
```

When I removed this everything worked again.

**Comment by rohitkrishna094** [comment]
For anyone who reached here, you might as well try this dumb solution(which happened to work for me).

Just click on prettier button in the bottom right of your vscode application.  😅

**Comment by acnevyts** [comment]
My problem was my editor.formatOnSaveTimeout config somehow got changed to 0. Found this out by checking in the 'Log (Window) Output' tab.

[2019-06-06 16:06:39.432] [renderer1] [warning] Aborted format on save after 0ms

increased it to 1000 and now its working fine.

**Comment by ramsanath** [comment]
In my case, I had this in my settings 
`"prettier.requireConfig": true`
which when I removed started working.

**Comment by JulianSoto** [comment]
Make sure Git is up to date

**Comment by patrickbattisti** [comment]
@ramsanath thanks, work for me

`"prettier.requireConfig": true`

**Comment by deloitte-erstevens** [comment]
@acnevyts thank you, this was my issue.

**Comment by d-e-v-esh** [comment]
I was having the same problem all of a sudden. I checked the box called indent lines with tabs under prettier in setting and checked another box called format on save under editors and that worked for. I am a beginner so I do not have much idea about any of this still and I just messed around the settings.

**Comment by klippx** [comment]
Yep, issue reappeared suddenly so it's good that I am still subscribed to this thread, checking "indent lines with tabs" seems to fix it this time over 😅 👍

**Comment by eminx** [comment]
For me the fix was simply going to the global settings at VS Code, and checking the field at:

**`Preferences >> Settings >> Text Editor >> Formatting >> Format on Save`** (check this!)

**Comment by metkerr** [comment]
> What happened in my case, is VSC update deleted some of my user settings, one of which was the `formatOnSave`
> , which is why the extension seemed broken ( as i'm used to format on save ).
> 
> Setting the property back was easy enough. If that's the case, check if you have
> `"editor.formatOnSave": true` set within the settings.

this work for me, thanks

**Comment by diorcula** [comment]
> For me the fix was simply going to the global settings at VS Code, and checking the field at:
> 
> **`Preferences >> Settings >> Text Editor >> Formatting >> Format on Save`** (check this!)

This worked for me, although i am not entirely sure if it uses prettier or standard formatting from [shift] + [alt] + [f]
